# Generated by Django 4.0.3 on 2022-03-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('description', models.TextField(verbose_name='Description here')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_info', models.DateTimeField(verbose_name='date published')),
                ('price_now', models.FloatField()),
                ('ask', models.FloatField()),
                ('bid', models.FloatField()),
                ('low_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('estimated_close_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getpapers.papers')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alerts', models.IntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getpapers.papers')),
            ],
        ),
    ]
