# Generated by Django 4.0.3 on 2022-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getpapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logmessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
